### ISSUE TITLE
ImportError: No module named 'treedict.treedict'

### ISSUE THREAD

**Issue by dessant** [hoytak/treedict#8]
I have installed the master branch with pip, cython was not used. I get this error with python 3.4 on windows:

`from treedict import TreeDict`

```
Traceback (most recent call last):
  File "C:\prs\main\test_2.py", line 165, in <module>
    from treedict import TreeDict
  File "C:\dev\python\lib\site-packages\treedict\__init__.py", line 1, in <module>
    from .treedict import TreeDict, getTree, treeExists, HashError
ImportError: No module named 'treedict.treedict'
```

**Comment by hoytak** [comment]
Hello dessant,

Apologies about the late reply -- I recently started a job, and only now am getting back to maintaining my open source projects. 

Did you get your question answered? I'm not sure what the problem would be. 

 -- Hoyt

**Comment by royw** [comment]
I hit the same problem with python 2.6, 2.7, 3.3, 3.4 virtualenvs.  What was happening is the old version on pypi is treedict-0.14.tar.gz while the latest version with python 3 support is treedict-0.2.2.tar.gz.  Pip says 14 > 2 so installs the old.  Work around is to explicitly "pip install treedict==0.2.2".
HTH

**Comment by hoytak** [comment]
Oh, oops!  It was supposed to be 0.1.4.  I'll try to do an update to 1.0
soon then.

-- Hoyt

++++++++++++++++++++++++++++++++++++++++++++++++
- Hoyt Koepke
- Data Scientist at GraphLab
- hoytak@gmail.com
  ++++++++++++++++++++++++++++++++++++++++++

**Comment by raunilillemets** [comment]
Had the same problem. Command "pip install treedict==0.2.2" helped. Any chance that this will be fixed soon?

**Comment by alertedsnake** [comment]
I'm also having the same version trying to install via pip using the Github repo as my source, as well as building with "python ./setup.py install" in a directory - even when using the 0.2.2 .tar.gz file fetched off pypi.

Turns out this is a little weird.  If you build and 'setup.py install' then you can't "import treedict" while you're in that same directory.  change directory elsewhere, no worries.

**Comment by frank-lzh** [comment]
Came across the same problem with python3 in Jupyter notebook, solved by "pip3 install treedict==0.2.2"

**Comment by alertedsnake** [comment]
Personally, at this point I'm using python-box because it isn't an
abandoned project. I suggest you do as well.

>
